FROM nvidia/cuda:12.6.3-base-ubuntu22.04

# Set environment variable for non-interactive apt-get installs
ENV DEBIAN_FRONTEND=noninteractive

ARG uid
ARG gid

RUN apt-get -y update && \
    apt-get -y install \
    	git \
    	python3 \
    	python3-venv \
    	libgl1 \
    	libglib2.0-0 \
    	libtcmalloc-minimal4
    	
RUN groupadd -r sdiff
RUN useradd -r -m -g sdiff sdiff
RUN usermod -u $uid sdiff
RUN groupmod -g $gid sdiff
RUN mkdir -p /stable-diffusion-webui
RUN chown -R sdiff:sdiff /stable-diffusion-webui
USER sdiff

RUN cd /stable-diffusion-webui
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui

WORKDIR /stable-diffusion-webui

ENTRYPOINT ["./webui.sh"]
CMD ["--listen", "--api", "--share"]
# --allow-code --medvram --xformers --enable-insecure-extension-access
